# DO NOT CHANGE the "init" and "install" sections below

# Download script file from GitHub
init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'

install:
  ps: Bootstrap

cache:
  - C:\RLibrary -> .appveyor.yml

# Adapt as necessary starting from here
environment:
  global:
      USE_RTOOLS: true
  matrix:
    - R_VERSION: devel
    - R_VERSION: release

build_script:
  - travis-tool.sh install_deps

test_script:
  - cinst ghostscript
  - cmd: set "GSPATH=C:\\Program Files\\gs\\gs9.50\\bin\\"
  - cmd: set "PATH=%GSPATH%;%PATH%"
  - cmd: gswin64c --version
  - travis-tool.sh run_tests

on_failure:
  - 7z a failure.zip *.Rcheck\*
  - appveyor PushArtifact failure.zip

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '*.Rcheck\**\*.Rout'
    name: Logs

  - path: '\*_*.tar.gz'
    name: Bits

  - path: '\*_*.zip'
    name: Bits
