language: r
cache:
  packages: true
  directories:
    - $HOME/Library/Caches/Homebrew
r:
    - release
    - devel 
os:
    - linux
    - osx
matrix:
    exclude:
        r: devel
        os: osx
sudo: false
latex: false
warnings_are_errors: true
cran: https://cran.rstudio.com
notifications:
  email:
    on_success: change
    on_failure: change
after_success:
    - Rscript -e 'covr::codecov()'
    - Rscript -e 'lintr::lint_package()'
addons:
    apt:
        packages:
            - libmagick++-dev
            - ghostscript
            - poppler-utils
r_github_packages:
  - r-lib/covr
  - jimhester/lintr
before_install:
    - if [ $TRAVIS_OS_NAME = osx ]; then brew install xpdf; fi
