#!/usr/bin/env Rscript

options(error = quote(dump.frames("last.dump", TRUE)))

suppressPackageStartupMessages(library("piecepack"))

collections <- get_collection()
# collections <- unique(get_collection(directories))


if (dir.exists("collections")) { unlink("collections", recursive=TRUE) }
dir.create("collections")

if (dir.exists("previews")) { unlink("previews", recursive=TRUE) }
dir.create("previews")

cl <- parallel::makeCluster(mc <- getOption("cl.cores", parallel::detectCores()))

# .po2 <- parallel::parLapply(cl, collections, make_preview)
.po2 <- lapply(collections, make_collection_preview)

# .po3 # parallel::parLapply(cl, collections, make_collection)
.p03 <- lapply(collections, make_collection)

invisible(NULL)
