#!/usr/bin/env Rscript

suppressPackageStartupMessages(library("piecepack"))

parser <- OptionParser("Program to make piecepack images")
opts <- parse_args(parser)

directories <- get_directories()

collections <- unique(get_collection(directories))

if (dir.exists("collections")) { unlink("collections", recursive=TRUE) }
dir.create("collections")

if (dir.exists("previews")) { unlink("previews", recursive=TRUE) }
dir.create("previews")

if (dir.exists("pdf")) { unlink("pdf", recursive=TRUE) }
dir.create("pdf")

cl <- parallel::makeCluster(mc <- getOption("cl.cores", parallel::detectCores()))

# .po1 <- parallel::parLapply(cl, directories, make_set)
.po1 <- lapply(directories, make_set)

# .po2 <- parallel::parLapply(cl, collections, make_preview)
.po2 <- lapply(collections, make_preview)

# # parallel::parLapply(cl, collections, make_collection)
lapply(collections, make_collection)

invisible(NULL)
