#!/usr/bin/env Rscript

options(error = quote(dump.frames("last.dump", TRUE)))

suppressPackageStartupMessages(library("piecepack"))

opts <- get_arrangement_opts()

dir.create("collections", showWarnings=FALSE)

dir.create("previews", showWarnings=FALSE)

make_collection_preview(opts)

make_collection(opts)

invisible(NULL)
