#!/usr/bin/env Rscript

options(error = quote(dump.frames("collect_dump", TRUE)))

suppressPackageStartupMessages(library("piecepack"))

opts <- get_arrangement_opts()

make_collection_preview(opts)

make_collection(opts)

invisible(NULL)
