#!/usr/bin/env Rscript

options(error = quote(dump.frames("collect_dump", TRUE)))

suppressPackageStartupMessages(library("optparse"))

parser <- OptionParser("Program to collect piecepacks")
parser <- add_option(parser, c('-o', '--output_filename'), default="%format/collections/%collection_name.%format",
     help='Output filename template (default "%default")')
parser <- add_option(parser, "--collection_name", default="piecepack_collection", help='Collection filename prefix (default "%default")')
parser <- add_option(parser, "--format", default="pdf", help='Currently only pdf is supported (default "%default")')

# Metadata to include
parser <- add_option(parser, "--author", default="",
                     help='Pdf author (default "")')
parser <- add_option(parser, "--keywords", default="piecepack",
                     help='Pdf keywords (default "%default")')
parser <- add_option(parser, "--subject", default="", 
                     help='Pdf subject (default "%default")')
####
parser <- add_option(parser, "--title", default=piecepackr:::get_title(), 
                     help='Pdf title (default "%default")')

parser <- add_option(parser, "--deck_names", default="",
                     help='Comma separated list of decks to collect')

parser <- add_option(parser, "--pdf_deck_dir", default=piecepackr:::get_pdf_deck_dir(),
                     help='(default "%default")')

parser <- add_option(parser, "--pdf_collection_dir", default=piecepackr:::get_pdf_collection_dir(),
                     help='(default "%default")')

parser <- add_option(parser, "--output_preview_dir", default=piecepackr:::get_pdf_preview_dir(),
                     help='(default "%default")')

parser <- add_option(parser, "--input_preview_dir", default=piecepackr:::get_svg_preview_dir(),
                     help='(default "svg/previews")')

parser <- add_option(parser, "--size", default="letter",
                     help='Pdf paper size, either "letter" or "A4" (default "%default")')
####
parser <- add_option(parser, "--font", default="sans", help='Default font family (default "%default")')

args <- parse_args(parser)

decks <- piecepackr::cleave(args$deck_names)
if(any(decks == "")) stop("Deck names unspecified") ####
output_preview_filename <- file.path(args$output_preview_dir, paste0(args$collection_name, ".", args$format))
input_preview_filenames <- file.path(args$input_preview_dir, paste0(decks, ".svg"))
piecepackr::make_collection_preview(output_preview_filename, input_preview_filenames, args$title, args$size)

output_filename <- gsub("%format", args$format, args$output_filename)
output_filename <- gsub("%collection_name", args$collection_name, output_filename)
deck_filenames <- file.path(args$pdf_deck_dir, paste0(decks, ".pdf"))
input_filenames <- c(output_preview_filename, deck_filenames)
piecepackr::make_collection(output_filename, input_filenames, args$size, args)

invisible(NULL)
