#!/usr/bin/env Rscript

suppressPackageStartupMessages(library("dplyr"))
suppressPackageStartupMessages(library("optparse"))
suppressPackageStartupMessages(library("piecepackr"))

cfg <- c2o()
default_chars <- c(piecepackr:::get_suit_symbols(NA, cfg), 
                    piecepackr:::get_rank_symbols(NA, cfg), 
                    piecepackr:::get_dm_symbols("coin_face", cfg),
                    piecepackr:::get_dm_symbols("saucer_face", cfg), 
                    piecepackr:::get_dm_symbols("chip_face", cfg), 
                    piecepackr:::get_dm_symbols("pawn_face", cfg)) 
default_chars <- paste(unique(default_chars), collapse=",")

parser <- OptionParser()
parser <- add_option(parser, c("-f", "--font"), default="sans", help='(comma separated) list of Fonts (default "%default")')
parser <- add_option(parser, c("-c", "--char"), default=default_chars, help='(comma separated) list of Characters (default = "%default"')
opts <- parse_args(parser)

font <- piecepack:::split(opts$font)
char <- piecepack:::split(opts$char)

df <- expand.grid(char, font, stringsAsFactors=FALSE)
names(df) <- c("char", "requested_font")
df <- dplyr::mutate(df, embedded_font = get_embedded_font(requested_font, char))
print(as.data.frame(dplyr::select(df, requested_font, embedded_font, char)))
