#!/usr/bin/env Rscript

options(error = quote(dump.frames("deck_dump", TRUE)), warn=2)

library("optparse")

parser <- OptionParser(description="Program to make print-and-play piecepack deck")
parser <- add_option(parser, c('-c', '--cfg_file'), default=NULL, help="Source of piecepack style information (default stdin input)")
parser <- add_option(parser, c('-o', '--output_filename'), default="%directory/%deck_name.%format",
     help='Output filename template (default "%default")')
parser <- add_option(parser, "--deck_name", default="piecepack_deck", help='Filename prefix (default "%default")')
parser <- add_option(parser, "--directory", default="%format/decks", help='Directory template (default "%default")')
parser <- add_option(parser, "--format", default="pdf", help='Currently only pdf is supported (default "%default")')
parser <- add_option(parser, "--size", default="letter", help='Either "letter" or "A4" (default "%default")')

args <- parse_args(parser)
directory <- gsub("%format", args$format, args$directory)
output_filename <- gsub("%directory", directory, args$output_filename)
output_filename <- gsub("%deck_name", args$deck_name, output_filename)
output_filename <- gsub("%format", args$format, output_filename)

cfg <- piecepackr::read_configuration(args$cfg_file)
piecepackr::make_pnp(cfg, output_filename, args$size)

invisible(NULL)
