#!/usr/bin/env Rscript

suppressPackageStartupMessages(library("piecepack"))
# library("optparse")

split <- function(x) { strsplit(x, "")[[1]] } 

parser <- OptionParser("Program to make piecepack images")
parser <- add_option(parser, "--set_name")
parser <- add_option(parser, "--suit_family")
parser <- add_option(parser, "--suit_symbols")
parser <- add_option(parser, "--rank_symbols")
parser <- add_option(parser, "--standardish", action="store_true")
opts <- parse_args(parser)


opts$parallel <- FALSE
opts$fast <- FALSE
opts$add_checkers <- FALSE
opts$add_bleed_lines <- FALSE
opts$background <- "seashell3"
# opts$background <- "brown"
# opts$background <- "white"
# opts$neutral_col1 <- "grey"
opts$neutral_col1 <- "grey60"
opts$neutral_col2 <- "yellow"
opts$rank_names <- c("n", "a", "2", "3", "4", "5")

opts$copyright <- "© 2017 Trevor L Davis. Some Rights Reserved."
opts$license1 <- "This work is licensed under a CC BY-SA 4.0 license:"
opts$license2 <- "https://creativecommons.org/licenses/by-sa/4.0/"
opts$suit_names <- c("s1", "s2", "s3", "s4")

opts$rank_symbols <- split(opts$rank_symbols)
opts$suit_symbols <- split(opts$suit_symbols)

# do.call(make_images_schemes, opts)
make_images_schemes(opts)

invisible(NULL)
