#!/usr/bin/env Rscript

options(error = quote(dump.frames("preview_dump", TRUE)), warn=2)

library("optparse")

parser <- OptionParser(description="Program to make piecpack previews")
parser <- add_option(parser, c('-c', '--cfg_file'), default=NULL, help="Source of piecepack style information (default stdin input)")
parser <- add_option(parser, "--deck_name", default="piecepack_deck", help='Filename prefix (default "%default")')
parser <- add_option(parser, "--directory", default="%format/previews", 
                help='Directory template (will sub in values for "%format" and "%deck_name") (default "%default")')
parser <- add_option(parser, "--formats", default="svg", help='Comma separated list of image formats (default "%default")')

args <- parse_args(parser)
cfg <- piecepackr::read_configuration(args$cfg_file)
formats <- piecepackr::split(args$formats)

for (format in formats) {
    directory <- gsub("%format", format, args$directory)
    directory <- gsub("%deck_name", args$deck_name, directory)
    output_filename <- file.path(directory, paste0(args$deck_name, ".", format))
    piecepackr::make_preview(cfg, output_filename)
}

invisible(NULL)
