#!/usr/bin/env Rscript

options(error = quote(dump.frames("preview_dump", TRUE)), warn=2)

suppressPackageStartupMessages(library("piecepack"))

opts <- read_style()
               
make_previews(opts)

invisible(NULL)
