#!/usr/bin/env Rscript

options(error = quote(dump.frames("last.dump", TRUE)))

suppressPackageStartupMessages(library("piecepack"))

opts <- get_options()
               
sublist <- opts[c("set_name", "copyright", "license1", "license2")]
cfilename <- sprintf("svg/%s.json", opts$set_label)

writeLines(rjson::toJSON(sublist), cfilename)

opts$directory <- sprintf("svg/%s", opts$deck_label)

make_images(opts)

make_set(opts)

invisible(NULL)
