#!/usr/bin/env Rscript

options(error = quote(dump.frames("deck_dump", TRUE)), warn=2)

suppressPackageStartupMessages(library("piecepack"))

opts <- read_configuration(description="Program to make print-and-play piecepack deck")

make_pnp_piecepack(opts)

invisible(NULL)
