#!/usr/bin/env Rscript

options(error = quote(dump.frames("preview_dump", TRUE)), warn=2)

suppressPackageStartupMessages(library("piecepack"))

opts <- read_configuration(description="Program to make piecepack preview")
               
make_piecepack_preview(opts)

invisible(NULL)
