#!/usr/bin/env Rscript

options(error = quote(dump.frames("images_dump", TRUE)), warn=2)

suppressPackageStartupMessages(library("piecepackr"))

opts <- read_configuration(description="Program to make piecepack component images")
               
make_piecepack_images(opts)

invisible(NULL)
