#!/usr/bin/env Rscript

options(error = quote(dump.frames("last.dump", TRUE)), warn=2)

suppressPackageStartupMessages(library("piecepack"))

opts <- read_style()
               
make_images(opts)

make_set(opts)

invisible(NULL)
