library("grid")
library("vdiffr")
context("pp_shape() works as expected")
test_that("pp_shape() works as expected", {
    circle <- pp_shape("circle")
    expect_error(grid.draw(circle$hexlines(gp=gpar(col="yellow"))))
    skip_on_ci()
    expect_doppelganger("add_checkers", function() {
        rect <- pp_shape("rect")
        pushViewport(viewport(width=0.9, height=0.9))
        grid.draw(rect$shape(gp=gpar(fill="grey", col="NA")))
        grid.draw(rect$checkers(gp=gpar(fill="purple")))
        grid.draw(rect$gridlines(gp=gpar(col="black")))
        grid.draw(rect$mat(mat_width = 0.05, gp=gpar(fill="green")))
        grid.draw(rect$hexlines(gp=gpar(col="yellow")))
        grid.draw(rect$shape(gp=gpar(col="black", fill="NA", lex=4)))
    })
    expect_doppelganger("add_checkers.transparent", function() {
        rect <- pp_shape("rect")
        grid.draw(rect$checkers(gp=gpar(fill="transparent")))
        grid.draw(rect$hexlines(gp=gpar(col="transparent")))
    })
    expect_doppelganger("add_checkers.convex8", function() {
        convex8 <- pp_shape("convex8", back = TRUE)
        pushViewport(viewport(width=0.9, height=0.9))
        grid.draw(convex8$shape(gp=gpar(fill="grey", col="NA")))
        grid.draw(convex8$checkers(gp=gpar(fill="purple")))
        grid.draw(convex8$gridlines(gp=gpar(col="black")))
        grid.draw(convex8$mat(mat_width = 0.05, gp=gpar(fill="green")))
        grid.draw(convex8$shape(gp=gpar(col="black", fill="NA", lex=4)))
    })
    expect_doppelganger("roundrect", function() {
        roundrect <- pp_shape("roundrect")
        pushViewport(viewport(width=0.9, height=0.9))
        grid.draw(roundrect$shape(gp=gpar(fill="grey", col="NA")))
        grid.draw(roundrect$checkers(gp=gpar(fill="purple")))
        grid.draw(roundrect$gridlines(gp=gpar(col="black")))
        grid.draw(roundrect$mat(mat_width = 0.05, gp=gpar(fill="green")))
        grid.draw(roundrect$hexlines(gp=gpar(col="yellow")))
        grid.draw(roundrect$shape(gp=gpar(col="black", fill="NA", lex=4)))
    })
    expect_doppelganger("circle", function() {
        circle <- pp_shape("circle")
        pushViewport(viewport(width=0.9, height=0.9))
        grid.draw(circle$shape(gp=gpar(fill="grey", col="NA")))
        grid.draw(circle$checkers(gp=gpar(fill="purple")))
        grid.draw(circle$mat(mat_width = 0.05, gp=gpar(fill="green")))
        # grid.draw(circle$hexlines(gp=gpar(col="yellow"))) # nolint
        # grid.draw(circle$gridlines(gp=gpar(col="black"))) # nolint
        grid.draw(circle$shape(gp=gpar(col="black", fill="NA", lex=4)))
    })
})
