# expect_that(, throws_error())

context("Test options are working")
test_that("options work as expected", {
    extra_flags <- c("--invert_colors.suited", "--background_colors=white",
                     "--suit_colors=darkred,black,darkgreen,darkblue,grey")
    opts <- c2o(extra_flags)
    expect_equal(get_suit_color("coin_back", 1, opts), "white")
    expect_equal(get_suit_color("coin_face", 5, opts), "grey")

    expect_equal(should_invert("coin_back", 1, c2o()), FALSE)
    expect_equal(should_invert("coin_back", 1, c2o("--invert_colors")), TRUE)
    expect_equal(should_invert("coin_back", 1, c2o("--invert_colors.suited")), TRUE)
    expect_equal(should_invert("coin_back", 1, c2o("--invert_colors.unsuited")), FALSE)
    expect_equal(should_invert("coin_back", 1, c2o("--invert_colors.coin_back")), TRUE)
    expect_equal(should_invert("coin_back", 1, c2o("--invert_colors.coin_face")), FALSE)
    expect_equal(should_invert("coin_back", 1, c2o("--uninvert_colors")), FALSE)
    expect_equal(should_invert("coin_face", 5, c2o()), FALSE)
    expect_equal(should_invert("coin_face", 5, c2o("--invert_colors")), TRUE)
    expect_equal(should_invert("coin_face", 5, c2o("--invert_colors.suited")), FALSE)
    expect_equal(should_invert("coin_face", 5, c2o("--invert_colors.unsuited")), TRUE)
    expect_equal(should_invert("coin_face", 5, c2o("--invert_colors.coin_back")), FALSE)
    expect_equal(should_invert("coin_face", 5, c2o("--invert_colors.coin_face")), TRUE)
    expect_equal(should_invert("coin_face", 5, c2o("--uninvert_colors")), FALSE)

    expect_equal(get_rank_symbol("chip_face", 1, 2, c2o(c("--suit_symbols=1,2,3,4,5", "--rank_symbols=A,B,C,D,E,F",
                                                       "--use_suit_as_ace"))), "1")
    args <- c("--rank_symbols=A,B,C,D,E,F", "--use_suit_as_ace", "--use_ace_as_ace.chip_face")
    expect_equal(c2o(args)$use_suit_as_ace.chip_face, FALSE)
    expect_equal(get_rank_symbol("chip_face", 1, 2, c2o(args)), "B")
    expect_equal(get_rank_symbol("ppdie_face", 6, 2, c2o(args)), "★")

    expect_equal(get_background_color("tile_face", 1, c2o("--background_colors.unsuited=orange")), "transparent")
    expect_equal(get_background_color("tile_back", 1, c2o("--background_colors.unsuited=orange")), "orange")
    expect_equal(is_suited("ppdie_face", 5, c2o()), TRUE)
    expect_equal(is_suited("ppdie_face", 6, c2o()), FALSE)
    expect_equal(get_background_color("ppdie_face", 5, c2o("--background_colors.unsuited=orange")), "transparent")
    expect_equal(get_background_color("ppdie_face", 6, c2o("--background_colors.unsuited=orange")), "orange")
    expect_equal(get_dm_symbol("suitdie_face", 3, c2o("--dm_symbols=")), "")
    expect_equal(get_dm_symbol("suitdie_face", 3, c2o("--dm_symbols=,,,,")), "")
    expect_equal(get_dm_symbol("suitdie_face", 6, c2o("--dm_symbols=")), "")
    expect_equal(get_dm_symbol("suitdie_face", 6, c2o("--dm_symbols=,,,,")), "")
    expect_equal(get_dm_symbol("ppdie_face", 6, c2o("--dm_symbols=,,,,")), "")
    expect_equal(get_dm_symbol("saucer_face", 3, c2o("--dm_symbols.saucer_face=b")), "b")
    expect_equal(get_dm_symbol("saucer_back", 5, c2o("--dm_symbols.saucer_back=b")), "b")
})
