test_that("options work as expected", {
    parser <- optparse::OptionParser()
    parser <- configuration_options(parser)

    cfg <- list(invert_colors.suited = TRUE,
                background_colors = "white",
                suit_colors = "darkred,black,darkgreen,darkblue,grey")
    expect_equal(get_suit_color("coin_back", 1, 1, cfg), "white")
    expect_equal(get_suit_color("coin_face", 5, 1, cfg), "grey")

    expect_equal(should_invert("coin_back", 1, 1, list()), FALSE)
    expect_equal(should_invert("coin_back", 1, 1, list(invert_colors = TRUE)), TRUE)
    expect_equal(should_invert("coin_back", 1, 1, list(invert_colors.suited = TRUE)), TRUE)
    expect_equal(should_invert("coin_back", 1, 1, list(invert_colors.unsuited = TRUE)), FALSE)
    expect_equal(should_invert("coin_back", 1, 1, list(invert_colors.coin_back = TRUE)), TRUE)
    expect_equal(should_invert("coin_back", 1, 1, list(invert_colors.coin_face = TRUE)), FALSE)
    expect_equal(should_invert("coin_back", 1, 1, list(invert_colors = FALSE)), FALSE)
    expect_equal(should_invert("coin_face", 5, 1, list()), FALSE)
    expect_equal(should_invert("coin_face", 5, 1, list(invert_colors = TRUE)), TRUE)
    expect_equal(should_invert("coin_face", 5, 1, list(invert_colors.suited = TRUE)), FALSE)
    expect_equal(should_invert("coin_face", 5, 1, list(invert_colors.unsuited = TRUE)), TRUE)
    expect_equal(should_invert("coin_face", 5, 1, list(invert_colors.coin_back = TRUE)), FALSE)
    expect_equal(should_invert("coin_face", 5, 1, list(invert_colors.coin_face = TRUE)), TRUE)
    expect_equal(should_invert("coin_face", 5, 1, list(invert_colors = FALSE)), FALSE)

    cfg <- list(suit_symbols="1,2,3,4,5",
                rank_symbols="A,B,C,D,E,F",
                use_suit_as_ace=TRUE)
    expect_equal(get_rank_symbol("chip_face", 1, 2, cfg), "1")
    cfg <- list(rank_symbols="A,B,C,D,E,F",
                use_suit_as_ace=TRUE,
                use_suit_as_ace.chip_face=FALSE)
    expect_equal(get_rank_symbol("chip_face", 1, 2, cfg), "B")
    expect_equal(get_rank_symbol("ppdie_face", 6, 2, cfg), "\u263c")

    cfg <- list(background_colors.unsuited="orange")
    expect_equal(get_background_color("tile_face", 1, 1, cfg), "white")
    expect_equal(get_background_color("tile_back", 1, 1, cfg), "orange")
    expect_equal(is_suited("ppdie_face", 5, 1, list()), TRUE)
    expect_equal(is_suited("ppdie_face", 6, 1, list()), FALSE)
    expect_equal(get_background_color("ppdie_face", 5, 1, cfg), "white")
    expect_equal(get_background_color("ppdie_face", 6, 1, cfg), "orange")
    cfg1 <- list(dm_symbols="")
    cfg2 <- list(dm_symbols=",,,,")
    expect_equal(get_dm_symbol("suitdie_face", 3, 1, cfg1), "")
    expect_equal(get_dm_symbol("suitdie_face", 3, 1, cfg2), "")
    expect_equal(get_dm_symbol("suitdie_face", 6, 1, cfg1), "")
    expect_equal(get_dm_symbol("suitdie_face", 6, 1, cfg2), "")
    expect_equal(get_dm_symbol("ppdie_face", 6, 1, cfg2), "")
    cfg <- list(dm_symbols.saucer_face="b")
    expect_equal(get_dm_symbol("saucer_face", 3, 1, cfg), "b")
    cfg <- list(dm_symbols.saucer_back="b")
    expect_equal(get_dm_symbol("saucer_back", 5, 1, cfg), "b")

    cfg <- list(invert_colors.suited=TRUE, invert_colors.r1=FALSE,
                suit_colors = "darkred,black,darkgreen,darkblue,grey")
    expect_equal(get_background_color("tile_face", 1, 2, cfg), "darkred")
    expect_equal(get_background_color("tile_face", 1, 1, cfg), "white")
})

context("get_component_opt works as expected")
test_that("get_component_opt works as expected", {
    opt <- get_component_opt("coin_face", 
                             cfg=list(suit_colors="darkred,black,darkgreen,darkblue,grey"))
    expect_equal(opt$bcol, "white")
    expect_equal(opt$scol, "grey")
    expect_equal(opt$border_col, "grey")
    expect_equal(opt$checker_col, "transparent")
    expect_equal(opt$gridline_col, "transparent") 
    expect_equal(opt$hexline_col, "transparent")
    expect_equal(opt$ps_symbol, "n")
    expect_equal(opt$ps_fontsize, 28)
    expect_equal(opt$ps_font, "sans")
    # expect_equal(opt$suit_symbol, "\u2605")
    # expect_equal(opt$suit_symbol, "\u263c")
    # expect_equal(opt$suit_fontsize, 24)
    # expect_equal(opt$suit_font, "sans")
    expect_equal(opt$dm_col, "grey")
    expect_equal(opt$dm_symbol, "\u25cf")
    expect_equal(opt$shape, "circle")
    expect_equal(opt$shape_fn, grid.circle)
    expect_equal(opt$shape_theta, 90)
    expect_equal(opt$dm_fontsize, 12)
    expect_equal(opt$dm_font, "sans")
    expect_equal(opt$dm_x, 0.5)
    expect_equal(opt$dm_y, to_y(90, sqrt(0.25^2 + 0.25^2)) + 0.5)
    expect_equal(opt$ps_x, 0.5)
    expect_equal(opt$ps_y, 0.5)

    opt <- get_component_opt("chip_back", i_s=1)
    # expect_equal(opt$dm_symbol, "\u2605")
    expect_equal(opt$dm_symbol, "\u2665")
    opt <- get_component_opt("saucer_back")
    expect_equal(opt$dm_symbol, "\u25b2")
    # expect_equal(opt$dm_symbol, "\u265f")
    opt <- get_component_opt("pawn_face")
    expect_equal(opt$dm_symbol, "\u0298\u0298")
    # expect_equal(opt$dm_symbol, "\U0001f440")
    opt <- get_component_opt("pawn_back")
    expect_equal(opt$dm_symbol, "")
})

context("load_configurations works as expected")
test_that("load_configurations works as expected", {
    cfg <- load_configurations(internal_cfgs = c("french_suits_white", "swirl_s5"))
    expect_equal(get_suit_symbol("saucer_face", 1, 1, cfg), "♡")
    expect_equal(get_suit_symbol("saucer_back", 5, 1, cfg), "꩜")
})
