split <- function(x, sep=",") { strsplit(x, sep)[[1]] } 

configuration_options <- function(args=commandArgs(TRUE)) {
    default_str <- "(default %default)"
    parser <- OptionParser("Program to make piecepack images")
    parser <- add_option(parser, "--set_label", default="collection", help=default_str)
    parser <- add_option(parser, "--set_name", default="set", help=default_str)
    parser <- add_option(parser, "--deck_label", default="deck", help=default_str)

    # Symbols
    parser <- add_option(parser, "--suit_symbols", default="♠,♥,♣,♦,★", help=default_str)
    parser <- add_option(parser, "--rank_symbols", default="NA2345", help=default_str)
    parser <- add_option(parser, "--rank_symbols.chip_face", default=NULL, help=default_str)

    # Style
    parser <- add_option(parser, "--directional_marker", default="neutral", 
                         help=paste("'neutral' use the neutral color, 'matching' use suit color on suit sides and neutral on neutral sides,",
                                    "'none' suppress direction mark (warning: can result in a non-conforming piecepack)",
                                    default_str))
    parser <- add_option(parser, "--use_suit_as_ace", action="store_true", default=FALSE, help=default_str)
    parser <- add_option(parser, "--style", default="basic", help=paste("'basic' or 'simple_hex'", default_str))

    # Color scheme
    parser <- add_option(parser, "--suit_colors", default="darkred,black,darkgreen,darkblue,grey", help=default_str)
    parser <- add_option(parser, "--background_color", default="white", help=default_str)
    parser <- add_option(parser, "--background_color.suited", default=NULL, help=default_str)
    parser <- add_option(parser, "--background_color.unsuited", default=NULL, help=default_str)
    #### Update
    parser <- add_option(parser, "--invert_colors", action="store_true", default=FALSE, help=default_str)
    parser <- add_option(parser, "--invert_colors.suited", action="store_true", default=NULL, help=default_str)
    parser <- add_option(parser, "--invert_colors.unsuited", action="store_true", default=NULL, help=default_str)
    parser <- add_option(parser, c("-f", "--file"), default=NULL, help="Filename to write style to (default outputs to standard output)")

    opts <- parse_args(parser, args)
    opts
}


#' @export
make_style <- function(args=commandArgs(TRUE)) {
    opts <- configuration_options(args)
    filename <- opts$file
    opts$file <- NULL
    opts$help <- NULL

    if (is.null(filename)) {
        writeLines(jsonlite::toJSON(opts, pretty=TRUE), stdout())
    } else {
        writeLines(jsonlite::toJSON(opts, pretty=TRUE), filename)
    }
}

process_configuration <- function(opts) {
    opts$parallel <- FALSE
    opts$fast <- TRUE
    opts$add_checkers <- FALSE
    opts$add_bleed_lines <- FALSE
    # opts$background <- "seashell3"
    # opts$background <- "tan"
    # opts$background <- "white"
    opts$rank_names <- c("n", "a", "2", "3", "4", "5")

    opts$program <- "Generated by the Configurable Piecepack PDF Maker."
    opts$copyright <- "© 2016-2018 Trevor L Davis. Some Rights Reserved."
    opts$license1 <- "This work is licensed under a CC BY-SA 4.0 license:"
    opts$license2 <- "https://creativecommons.org/licenses/by-sa/4.0/"

    opts$rank_symbols <- split(opts$rank_symbols)
    opts$suit_colors <- split(opts$suit_colors)
    opts$suit_symbols <- split(opts$suit_symbols)
    if (is.null(opts$rank_symbols.chip_face)) 
        opts$rank_symbols.chip_face <- opts$rank_symbols
    else
        opts$rank_symbols.chip_face <- split(opts$rank_symbols.chip_face)

    # opts$suit_colors <- c("dimgrey", "hotpink2", "darkolivegreen3", "lightblue2")
    # opts$suit_colors <- c("white", "orange2", "yellow", "purple")
    # opts$suit_colors <- rep(c("black", "darkred"), 2)
    # opts$suit_colors <- rep(c("dimgrey", "hotpink2"), 2)
    # opts$suit_colors <- rep(c("white", "orange2"), 2)
    # opts$suit_colors <- rep(c("black"), 4)
    # opts$suit_colors <- rep(c("dimgrey"), 4)
    # opts$suit_colors <- rep(c("white"), 4)
    # opts$suit_colors <- c("black", "darkred", "darkgreen", "darkblue")
    # opts$suit_colors <- c("dimgrey", "hotpink2", "darkolivegreen3", "lightblue2")
    # opts$suit_colors <- c("white", "orange2", "yellow", "purple")
    # opts$suit_colors <- rep(c("black", "darkred"), 2)
    # opts$suit_colors <- rep(c("dimgrey", "hotpink2"), 2)
    # opts$suit_colors <- rep(c("white", "orange2"), 2)
    # opts$suit_colors <- rep(c("black"), 4)
    # opts$suit_colors <- rep(c("dimgrey"), 4)
    # opts$suit_colors <- rep(c("white"), 4)

    opts
}

#' @export
read_style <- function(args=commandArgs(TRUE)) {
    parser <- OptionParser()
    parser <- add_option(parser, c('-f', '--file'), default=NULL, help="Source of piecepack style information (default stdin input)")
    opts <- parse_args(parser, args)

    if (is.null(opts$file)) 
        con <- file("stdin")
    else 
        con <- file(opts$file)
    
    opts <- jsonlite::fromJSON(readLines(con))
    close(con)

    opts <- process_configuration(opts)
    opts
}


