split <- function(x, sep=",") { strsplit(x, sep)[[1]] } 

#' @export
make_style <- function(args=commandArgs(TRUE)) {
    parser <- OptionParser("Program to make piecepack images")
    parser <- add_option(parser, "--set_label", default="collection")
    parser <- add_option(parser, "--set_name", default="set")
    parser <- add_option(parser, "--deck_label", default="deck")
    parser <- add_option(parser, "--suit_colors", default="darkred,black,darkgreen,darkblue,grey")
    # parser <- add_option(parser, "--background", default="seashell3")
    parser <- add_option(parser, "--background_color", default="white")
    parser <- add_option(parser, "--directional_marker", default="neutral", help="'neutral' use the neutral color, 'matching' use suit color on suit sides and neutral on neutral sides, 'none' suppress direction mark (warning: can result in a non-conforming piecepack)")
    parser <- add_option(parser, "--suit_symbols", default="♠,♥,♣,♦,★")
    parser <- add_option(parser, "--rank_symbols", default="NA2345")
    parser <- add_option(parser, "--rank_symbols.chip_face", default=NULL, help="Rank symbols for 'chips', defaults to what ``rank_symbols`` is set to. 'A,B,C,D,E,F' is good if building piecepack pyramids.")
    parser <- add_option(parser, "--style", default="basic", help="'basic' or 'simple_hex'")
    parser <- add_option(parser, "--use_suit_as_ace", action="store_true", default=FALSE)
    parser <- add_option(parser, "--invert_colors.suited", action="store_true", default=FALSE)
    parser <- add_option(parser, c("-f", "--file"), default=NULL, help="Filename to write style to (default outputs to standard output)")
    opts <- parse_args(parser, args)
    filename <- opts$file
    opts$file <- NULL
    opts$help <- NULL

    if (is.null(filename)) {
        writeLines(jsonlite::toJSON(opts, pretty=TRUE), stdout())
    } else {
        writeLines(jsonlite::toJSON(opts, pretty=TRUE), filename)
    }
}

#' @export

read_style <- function(args=commandArgs(TRUE)) {
    parser <- OptionParser()
    parser <- add_option(parser, c('-f', '--file'), default=NULL, help="Source of piecepack style information (default stdin input)")
    opts <- parse_args(parser, args)

    if (is.null(opts$file)) 
        con <- file("stdin")
    else 
        con <- file(opts$file)
    
    opts <- jsonlite::fromJSON(readLines(con))
    close(con)

    opts$parallel <- FALSE
    opts$fast <- TRUE
    opts$add_checkers <- FALSE
    opts$add_bleed_lines <- FALSE
    # opts$background <- "seashell3"
    # opts$background <- "tan"
    # opts$background <- "white"
    opts$rank_names <- c("n", "a", "2", "3", "4", "5")

    opts$program <- "Generated by the Configurable Piecepack PDF Maker."
    opts$copyright <- "© 2016-2018 Trevor L Davis. Some Rights Reserved."
    opts$license1 <- "This work is licensed under a CC BY-SA 4.0 license:"
    opts$license2 <- "https://creativecommons.org/licenses/by-sa/4.0/"

    opts$rank_symbols <- split(opts$rank_symbols)
    opts$suit_colors <- split(opts$suit_colors)
    opts$suit_symbols <- split(opts$suit_symbols)
    if (is.null(opts$rank_symbols.chip_face)) 
        opts$rank_symbols.chip_face <- opts$rank_symbols
    else
        opts$rank_symbols.chip_face <- split(opts$rank_symbols.chip_face)

    # opts$suit_colors <- c("dimgrey", "hotpink2", "darkolivegreen3", "lightblue2")
    # opts$suit_colors <- c("white", "orange2", "yellow", "purple")
    # opts$suit_colors <- rep(c("black", "darkred"), 2)
    # opts$suit_colors <- rep(c("dimgrey", "hotpink2"), 2)
    # opts$suit_colors <- rep(c("white", "orange2"), 2)
    # opts$suit_colors <- rep(c("black"), 4)
    # opts$suit_colors <- rep(c("dimgrey"), 4)
    # opts$suit_colors <- rep(c("white"), 4)
    # opts$suit_colors <- c("black", "darkred", "darkgreen", "darkblue")
    # opts$suit_colors <- c("dimgrey", "hotpink2", "darkolivegreen3", "lightblue2")
    # opts$suit_colors <- c("white", "orange2", "yellow", "purple")
    # opts$suit_colors <- rep(c("black", "darkred"), 2)
    # opts$suit_colors <- rep(c("dimgrey", "hotpink2"), 2)
    # opts$suit_colors <- rep(c("white", "orange2"), 2)
    # opts$suit_colors <- rep(c("black"), 4)
    # opts$suit_colors <- rep(c("dimgrey"), 4)
    # opts$suit_colors <- rep(c("white"), 4)

    opts
}
