#' @importFrom grImport2 pictureGrob readPicture
cc_file <- pictureGrob(readPicture(system.file("extdata/by-sa-svg.svg", package="piecepackr")))

is_odd <- function(x) { as.logical(x %% 2) }

#' Inch utility function
#'
#' This utility function is equivalent to \code{grid::unit(x, "in")}.
#' 
#' @param x Number representing number of inches
#' @export
inch <- function(x) { unit(x, "in") }

make_get_style_fn <- function(style, default) {
    function(cfg=list()) get_style_element(style, cfg=cfg, default=default)
}

get_pp_die_arrangement <- function(component_side=NA, cfg=list()) {
    get_style_element("pp_die_arrangement", component_side, cfg, "counter")
}

get_font <- make_get_style_fn("font", "sans")
get_scale <- make_get_style_fn("scale", 1.0)

#### 
get_deck_filename <- make_get_style_fn("deck_filename", "piecepack_deck")
get_pdf_deck_dir <- make_get_style_fn("pdf_deck_dir", "pdf/decks")
get_pdf_collection_dir <- make_get_style_fn("pdf_collection_dir", "pdf/collections")
get_pdf_preview_dir <- make_get_style_fn("pdf_preview_dir", "pdf/previews")
get_svg_preview_dir <- make_get_style_fn("svg_preview_dir", "svg/previews")
get_paper <- make_get_style_fn("paper", "letter")
get_decks <- function(cfg=list()) {
    default <- paste(gsub(".pdf$", "", list.files(get_pdf_deck_dir(cfg))), collapse=",")
    cleave(make_get_style_fn("decks", default)(cfg))
}
get_program <- function(cfg=list()) { "Generated by the piecepackr R package." }
get_copyright <- function(cfg=list()) { "\u00a9 2016-2018 Trevor L Davis. Some Rights Reserved." }
get_license1 <- function(cfg=list()) { "This work is licensed under a CC BY-SA 4.0 license:" }
get_license2 <- function(cfg=list()) { "https://creativecommons.org/licenses/by-sa/4.0/" }
get_title <- make_get_style_fn("title", "Piecepack collection")

make_4by3_viewports <- function(label) {
    for (i_row in 1:3) {
        i_l_rank <- 2 * (i_row-1) + 1
        i_r_rank <- 2 * (i_row-1) + 2
        addViewport(y=(4-i_row)/3-1/6, height=1/3, name=paste0(label, ".row.", i_row))
        downViewport(paste0(label, ".row.", i_row))
        addViewport(x=0.125, width=0.25, name=paste0(label, ".face.", i_l_rank))
        addViewport(x=0.375, width=0.25, name=paste0(label, ".back.", i_l_rank))
        addViewport(x=0.625, width=0.25, name=paste0(label, ".face.", i_r_rank))
        addViewport(x=0.875, width=0.25, name=paste0(label, ".back.", i_r_rank))
        upViewport()
    }
}

draw_coin_4by3 <- function(i_s, cfg) {
    label <- stringi::stri_rand_strings(n=1, length=4)
    make_4by3_viewports(label)
    for(i_r in 1:6) {
        seekViewport(paste0(label, ".back.", i_r))
        draw_component("coin_back", cfg, i_s)
        seekViewport(paste0(label, ".face.", i_r))
        draw_component("coin_face", cfg, i_r=i_r)
    }
}

x_die_layoutRF <- c(1/4, 2/4, 2/4, 3/4, 3/4, 4/4) - 1/8
x_die_layoutLF <- c(4/4, 3/4, 3/4, 2/4, 2/4, 1/4) - 1/8
y_die_layout <- c(1/3, 1/3, 2/3, 2/3, 3/3, 3/3) - 1/6

draw_die_layoutRF <- function(component_side, i_s, i_r, cfg) {
    draw_piecepack_die(i_s, cfg)
}

draw_die_layoutLF <- function(component_side, i_s, i_r, cfg) {
    draw_piecepack_die(i_s, cfg, flip=TRUE)
}

draw_suitdie_layoutRF <- function(component_side, i_s, i_r, cfg) {
    draw_suit_die(cfg)
}

draw_suitdie_layoutLF <- function(component_side, i_s, i_r, cfg) {
    draw_suit_die(cfg, flip=TRUE)
}

draw_suitrankdie_layoutRF <- function(component_side, i_s, i_r, cfg) {
    draw_suitrank_die(cfg)
}
draw_suitrankdie_layoutLF <- function(component_side, i_s, i_r, cfg) {
    draw_suitrank_die(cfg, flip=TRUE)
}

draw_piecepack_die <- function(i_s, cfg, flip=FALSE) {
    angle <- rep(c(-90, 0), 3)
    if (flip) {
        x <- x_die_layoutLF
        angle <- -angle
    } else {
        x <- x_die_layoutRF
    }
    if (get_pp_die_arrangement(cfg=cfg) == "opposites_sum_to_5") {
        i_r <- c(1, 2, 3, 6, 5, 4)
        i_s <- rep(i_s, length.out=6)[i_r]
    } else {
        i_r <- 1:6
    }
    df <- tibble::data_frame(component_side="die_face", i_s, i_r, x, y=y_die_layout, angle)
    draw_components(df, cfg=cfg)
}

draw_suit_die <- function(cfg, flip=FALSE) {
    angle <- rep(c(-90, 0), 3)
    if (flip) {
        x <- x_die_layoutLF
        angle <- -angle
    } else {
        x <- x_die_layoutRF
    }
    i_s <- get_suit_die_suits(cfg)
    df <- tibble::data_frame(component_side="suitdie_face", i_s, x, y=y_die_layout, angle)
    draw_components(df, cfg=cfg)
}

get_suit_die_suits <- function(cfg) {
    n_suits <- get_n_suits(cfg)
    if (n_suits < 4) {
        rep(n_suits:1, length.out=6)
    } else if (n_suits == 4) {
        c(5,6,4:1)
    } else if (n_suits > 4) {
        6:1
    } 
}

draw_suitrank_die <- function(cfg, flip=FALSE) {
    i_s <- get_suit_die_suits(cfg)
    draw_piecepack_die(i_s, cfg, flip)
}

#### Get rid of cfg?
make_header_helper <- function(cfg, title) {
    header_height <- 0.8
    y_header <- WIN_HEIGHT - header_height/2
    width_image = 0.14
    gp <- gpar(fontsize=9, fontfamily="sans")
    gp_title <- gpar(fontsize=15, fontfamily="sans", fontface="bold")
    pushViewport(viewport(y=inch(y_header), width=inch(6.0), height=inch(header_height)))
    # title
    pushViewport(viewport(y=0.85, height=0.2))
    grid.text(title, just="center", gp=gp_title)
    popViewport()
    # CC images
    pushViewport(viewport(x=width_image/2, y=0.4, width=width_image, height=0.5))
    grid.draw(cc_file)
    popViewport()
    pushViewport(viewport(x=1-width_image/2, y=0.4, width=width_image, height=0.5))
    grid.draw(cc_file)
    popViewport()
    # text
    pushViewport(viewport(x=0.5, y=0.4, width=1-2*width_image, height=0.8))
    grid.text(get_program(cfg), x=0.5, y=0.8, just="center", gp=gp)
    grid.text(get_copyright(cfg), x=0.5, y=0.6, just="center", gp=gp)
    grid.text(get_license1(cfg), x=0.5, y=0.4, just="center", gp=gp)
    grid.text(get_license2(cfg), x=0.5, y=0.2, just="center", gp=gp)
    popViewport()
    popViewport()
}

seekViewport <- function(...) { suppressWarnings(grid::seekViewport(...)) }

pp_pdf <- function(filename, family, paper) {
    if (paper == "letter") {
        cairo_pdf(filename, onefile=TRUE, width=8.5, height=11, family=family)
    } else if (paper == "A4") {
        cairo_pdf(filename, onefile=TRUE, width=8.3, height=11.7, family=family)
    } else {
        stop(paste("Don't know how to handle paper", paper))
    }
}

#' Make collection preview
#' 
#' Makes a preview pdf of a collection of pnp decks.
#'
#' @param output_filename Filename of PnP output
#' @param input_filenames Vector of input filenames
#' @param title Title of collection
#' @param size PnP output size (currently either "letter" or "A4")
#' @export
make_collection_preview <- function(output_filename, input_filenames, title="", size="letter") {
    unlink(output_filename)
    directory <- dirname(output_filename)
    dir.create(directory, recursive=TRUE, showWarnings=FALSE)

    
    cfg <- list() #### Remove cfg?
    pp_pdf(output_filename, "sans", size)

    n_pages <- ceiling(length(input_filenames) / 6)

    for (ii in 1:n_pages) {

        jj <- (ii - 1) * 6 + 1

        l_logos <- list()
        for(kk in 0:5) {
            filename <- input_filenames[jj+kk]
            if(is.na(filename))
                l_logos[[kk+1]] <- nullGrob()
            else
                l_logos[[kk+1]] <- pictureGrob(readPicture(filename, warn=FALSE))
        }
        l_squares <- lapply(seq(along=l_logos), function(x) { rectGrob(gp=gpar(lty="dashed", col="grey", fill=NA)) })
        grid.newpage()
        vp <- viewport(x=inch(4.25), y=inch(5.0), width=inch(8), height=inch(8)) 
        pushViewport(vp)
        gridExtra::grid.arrange(grobs=l_logos, ncol=2, newpage=FALSE, padding=0)
        gridExtra::grid.arrange(grobs=l_squares, ncol=2, newpage=FALSE, padding=0)
        upViewport()
        make_header_helper(cfg, title)
    }

    if (is_odd(n_pages)) {
        grid.newpage()
        grid.text("This page intentionally left blank")
    }
    invisible(dev.off())
}

WIN_WIDTH <- 8
WIN_HEIGHT <- 10.5

draw_suit_page <- function(i_s, cfg=list(), deck_title="") {
    pushViewport(viewport(width=inch(WIN_WIDTH), height=inch(WIN_HEIGHT), name="main"))
    make_header_helper(cfg, deck_title)

    i_unsuit <- get_i_unsuit(cfg)
    xdie <- PAWN_WIDTH + 3*DIE_WIDTH/2 
    ydie <- 3*TILE_WIDTH + 4*DIE_WIDTH/2
    ydie2 <- ydie + 2*DIE_WIDTH 
    ybelt <- ydie2 + 2*DIE_WIDTH + DIE_WIDTH/2
    xbelt <- BELT_WIDTH/2
    ysaucer <- 3*TILE_WIDTH + SAUCER_WIDTH/2
    xpawn <- PAWN_WIDTH/2
    pheight <- PAWN_LAYOUT_HEIGHT
    ypawn <- 3*TILE_WIDTH + pheight/2 
    df <- tibble::tribble( ~component_side, ~x, ~y, ~i_s, ~i_r,
                          "tile_face", 1, 5, i_s, 1,
                          "tile_face", 5, 5, i_s, 2,
                          "tile_face", 1, 3, i_s, 3,
                          "tile_face", 5, 3, i_s, 4,
                          "tile_face", 1, 1, i_s, 5,
                          "tile_face", 5, 1, i_s, 6,
                          "tile_back", 3, 1, i_unsuit, 0,
                          "tile_back", 7, 1, i_unsuit, 0,
                          "tile_back", 3, 3, i_unsuit, 0,
                          "tile_back", 7, 3, i_unsuit, 0,
                          "tile_back", 3, 5, i_unsuit, 0,
                          "tile_back", 7, 5, i_unsuit, 0,
                          "belt_face", xbelt, ybelt, i_s, 0,
                          "belt_face", WIN_WIDTH-xbelt, ybelt, i_s, 0,
                          "saucer_face", 4-0.5*SAUCER_WIDTH, ysaucer, i_s, 0,
                          "saucer_face", 4+1.5*SAUCER_WIDTH, ysaucer, i_s, 0,
                          "saucer_back", 4-1.5*SAUCER_WIDTH, ysaucer, i_unsuit, 0,
                          "saucer_back", 4+0.5*SAUCER_WIDTH, ysaucer, i_unsuit, 0,
                          "pawn_layout", WIN_WIDTH-xpawn, ypawn, i_s, 0
                          )
    draw_components(df, cfg=cfg, units="inches")
    draw_component("pawn_layout", cfg, i_s, x=inch(xpawn), y=inch(ypawn), angle=180) 
    draw_component("die_layoutLF", cfg, i_s, x=inch(xdie), y=inch(ydie), angle=-90)
    draw_component("die_layoutRF", cfg, i_s, x=inch(WIN_WIDTH-xdie), y=inch(ydie), angle=90)
    draw_component("die_layoutLF", cfg, i_s, x=inch(xdie), y=inch(ydie2), angle=-90)
    draw_component("die_layoutRF", cfg, i_s, x=inch(WIN_WIDTH-xdie), y=inch(ydie2), angle=90)

    # coins
    ycoin <- ysaucer + SAUCER_WIDTH/2 + 3*COIN_WIDTH/2
    pushViewport(viewport(y=inch(ycoin), width=inch(4 * COIN_WIDTH), height=inch(3 * COIN_WIDTH)))
    draw_coin_4by3(i_s, cfg)
    popViewport()

    invisible(NULL)
}

draw_accessories_page <- function(cfg, deck_title="", odd=TRUE) {
    pushViewport(viewport(width=inch(WIN_WIDTH), height=inch(WIN_HEIGHT), name="main"))
    make_header_helper(cfg, deck_title)

    n_ranks <- get_n_ranks(cfg)
    n_suits <- get_n_suits(cfg)
    i_unsuit <- n_suits + 1


    # Joker Tile
    y_joker <- 8.75
    pushViewport(viewport(y=inch(y_joker), x=0.5, width=inch(2*TILE_WIDTH), height=inch(TILE_WIDTH)))
    draw_component("tile_face", cfg, i_unsuit, n_ranks + 1, x=0.25) ####
    draw_component("tile_back", cfg, x=0.75)
    popViewport()

    ## dice
    ydh <- y_joker - DIE_WIDTH/2 + DIE_WIDTH
    ydm <- ydh - 3 * DIE_WIDTH
    ydl <- ydm - 3 * DIE_WIDTH
    ydb <- ydl - 3 * DIE_WIDTH
    die_xl = 2*DIE_WIDTH
    die_xm = die_xl + 2*DIE_WIDTH
    die_xh = die_xm + 2*DIE_WIDTH

    # extra standard piecepack dice
    die_x <- c(die_xl, die_xm, die_xm, die_xl, die_xh, die_xh)
    die_y <- c(ydl, ydl, ydb, ydb, ydl, ydb)
    for (i_s in 1:n_suits) {
        draw_component("die_layoutLF", cfg, i_s, y=inch(die_y[i_s]), x=inch(die_x[i_s]))
    }

    # rank dice
    draw_component("die_layoutRF", cfg, i_unsuit+1, y=inch(ydl), x=inch(WIN_WIDTH-die_xl))
    draw_component("die_layoutRF", cfg, i_unsuit+1, y=inch(ydl), x=inch(WIN_WIDTH-die_xm))
    draw_component("die_layoutRF", cfg, i_unsuit+1, y=inch(ydl), x=inch(WIN_WIDTH-die_xh))
    if (n_suits < 5) 
        draw_component("die_layoutLF", cfg, i_unsuit+1, y=inch(ydl), x=inch(die_xh))
    draw_component("die_layoutRF", cfg, i_unsuit+1, y=inch(ydb), x=inch(WIN_WIDTH-die_xl))
    draw_component("die_layoutRF", cfg, i_unsuit+1, y=inch(ydb), x=inch(WIN_WIDTH-die_xm))
    draw_component("die_layoutRF", cfg, i_unsuit+1, y=inch(ydb), x=inch(WIN_WIDTH-die_xh))
    if (n_suits < 6) 
        draw_component("die_layoutLF", cfg, i_unsuit+1, y=inch(ydb), x=inch(die_xh))

    # suit dice and suit/rank dice
    addViewport(y=inch(ydh), x=inch(die_xl), width=inch(2), height=inch(1.5), name="lsuitdie")
    addViewport(y=inch(ydh), x=inch(WIN_WIDTH-die_xl), width=inch(2), height=inch(1.5), name="rsuitdie")
    addViewport(y=inch(ydm-DIE_WIDTH), width=inch(2), height=inch(1.5), name="suitdie3")
    addViewport(y=inch(ydm), x=inch(WIN_WIDTH-die_xl), width=inch(2), height=inch(1.5), name="suitrankdie1")
    addViewport(y=inch(ydm), x=inch(WIN_WIDTH-die_xm), width=inch(2), height=inch(1.5), name="suitrankdie2")
    addViewport(y=inch(ydm), x=inch(die_xl), width=inch(2), height=inch(1.5), name="suitrankdie3")
    addViewport(y=inch(ydm), x=inch(die_xm), width=inch(2), height=inch(1.5), name="suitrankdie4")


    for (i_s in 1:n_suits) {
        pushViewport(viewport(y=inch((n_suits + 1 - i_s)*CHIP_WIDTH - 0.5*CHIP_WIDTH), 
                    width=inch(12*CHIP_WIDTH), height=inch(CHIP_WIDTH)))
        for (i_r in 1:6) {
            draw_component("chip_back", cfg, i_s,      x=(2*i_r-1)/12-1/24)
            draw_component("chip_face", cfg, i_s, i_r, x=(2*i_r  )/12-1/24)
        }
        popViewport()
    }
    if (n_suits <= 4) {
        saucer_y <- 4*CHIP_WIDTH + 0.5*SAUCER_WIDTH + 0.125
        pushViewport(viewport(y=inch(saucer_y),width=inch(8*SAUCER_WIDTH), height=inch(SAUCER_WIDTH)))
        for (i_s in 1:n_suits) {
            draw_component("saucer_face", cfg, i_s, x=(2*i_s-1)/8-1/16)
            draw_component("saucer_back", cfg,      x=(2*i_s  )/8-1/16)
        }
        popViewport()
    }

    # Draw components
    seekViewport("rsuitdie")
    draw_suit_die(cfg)
    seekViewport("lsuitdie")
    draw_suit_die(cfg, flip=TRUE)
    seekViewport("suitdie3")
    if (odd)
        draw_suit_die(cfg)
    else
        draw_suit_die(cfg, flip=TRUE)
    seekViewport("suitrankdie1")
     draw_suitrank_die(cfg)
    seekViewport("suitrankdie2")
     draw_suitrank_die(cfg)
    seekViewport("suitrankdie3")
     draw_suitrank_die(cfg, flip=TRUE)
    seekViewport("suitrankdie4")
     draw_suitrank_die(cfg, flip=TRUE)

    invisible(NULL)
}

#' Make print-and-play piecepack pdf
#'
#' Makes a print-and-play piecepack pdf.
#'
#' @param cfg Piecepack configuration list
#' @param output_filename Filename of PnP output
#' @param size PnP output size (currently either "letter" or "A4")
#' @param deck_title Title of deck
#' @param components Character vector of desired PnP components (default everything)
#' @export
make_pnp <- function(cfg=list(), output_filename="pdf/decks/piecepack_deck.pdf", size="letter", 
                     deck_title = "",
                     components=c("piecepack", "misc")) {
    unlink(output_filename)
    directory <- dirname(output_filename)
    dir.create(directory, recursive=TRUE, showWarnings=FALSE)

    n_suits <- get_n_suits(cfg)
    i_unsuit <- n_suits + 1
    cfg <- pp_cfg(cfg)

    pp_pdf(output_filename, get_font(cfg), size)

    if ("piecepack" %in% components) {
        for (i_s in 1:n_suits) {
            grid.newpage()
            draw_suit_page(i_s, cfg, deck_title)
        }
        if (is_odd(n_suits)) {
            grid.newpage()
            draw_suit_page(i_unsuit+1, cfg, deck_title)
        }
    }

    if ("misc" %in% components) {
        if ((n_suits >= 4) && (n_suits <= 6)) {
            grid.newpage()
            draw_accessories_page(cfg, deck_title)
            grid.newpage()
            draw_accessories_page(cfg, deck_title, odd=FALSE)
        }
    }
    invisible(dev.off())
}

make_pdfmark_txt <- function(pm_filename, input_filenames) {
    deck_filenames <- input_filenames[-1]
    n_sets <- length(deck_filenames) 

    n_preview <- ceiling(n_sets / 6)
    if (is_odd(n_preview))
        n_preview <- n_preview + 1
    txt <- "[/Page 1 /View [/XYZ null null null] /Title (Piecepack Sets Preview) /OUT pdfmark"
    next_page <- n_preview + 1
    for(ii in 1:n_sets) {
        new_txt <- sprintf("[/Page %s /View [/XYZ null null null] /Title (Piecepack Set #%s) /OUT pdfmark", next_page, ii)
        txt <- append(txt, new_txt)
        next_page <- next_page + get_n_pages(deck_filenames[ii])
    }
    writeLines(txt, pm_filename)
}

make_pdfmark_metadata <- function(pm_filename, title="Piecepack collection", author="", subject="", keywords="piecepack") {
    txt <- paste0("[ /Title (", title, ")\n /Author (", author, ")\n /Subject (", 
                subject, ")\n /Keywords (", keywords, ")\n /DOCINFO pdfmark")

    writeLines(txt, pm_filename)
}

get_n_pages_pdfinfo <- function(pdf_filename) {
    pdf_filename <- shQuote(normalizePath(pdf_filename))
    pdfinfo <- system2("pdfinfo", pdf_filename, stdout=TRUE)
    pdfinfo <- grep("^Pages:", pdfinfo, value=TRUE)
    as.numeric(strsplit(pdfinfo, " +")[[1]][2])
}
get_n_pages_gs <- function(pdf_filename) {
    pdf_filename <- normalizePath(pdf_filename, winslash="/")
    cmd <- find_gs()
    args <- c("-q", "-dNODISPLAY", "-c", paste(paste0('"(', pdf_filename, ")"),
              "(r)", "file", "runpdfbegin", "pdfpagecount", "=", 'quit"'))
    as.numeric(system2(cmd, args, stdout=TRUE))
}
get_n_pages <- function(pdf_filename) {
    if (Sys.which("pdfinfo") != "") {
        np <- get_n_pages_pdfinfo(pdf_filename)
    } else {
        np <- get_n_pages_gs(pdf_filename)
    }
    np
}

#' Collects print-and-play piecepack pdfs into one pdf
#'
#' Collects print-and-play piecepack pdfs into one pdf
#' with a preview at the beginning.
#'
#' @param output_filename Filename of PnP output
#' @param input_filenames Vector of input filenames (starting with preview pdf)
#' @param size PnP output size (currently either "letter" or "A4")
#' @param metadata List of metadata to embed
#' @export
make_collection <- function(output_filename, input_filenames, size="letter", metadata=list()) {
    unlink(output_filename)
    directory <- dirname(output_filename)
    dir.create(directory, recursive=TRUE, showWarnings=FALSE)

    # add bookmarks
    pm_filename <- tempfile(fileext=".txt")
    make_pdfmark_txt(pm_filename, input_filenames)

    temp_pdf <- tempfile(fileext=".pdf")
    cmd <- find_gs()
    args <- c("-q", "-o", shQuote(temp_pdf), "-sDEVICE=pdfwrite", pm_filename, shQuote(input_filenames))
    system2(cmd, args)

    #### What to do with metadata
    pm_filename <- tempfile(fileext=".txt")
    make_pdfmark_metadata(pm_filename, metadata$title, metadata$author, metadata$subject, metadata$keywords)
    args <- c("-q", "-o", shQuote(output_filename), "-sDEVICE=pdfwrite", pm_filename, shQuote(temp_pdf))
    system2(cmd, args)

}

find_gs <- function() {
    cmd <- tools::find_gs_cmd()
    if (cmd == "") 
        stop("Can't find system dependency ghostscript on PATH")
    cmd
}
